config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', confirmations: 'confirmations' }

  root to: "questions#index"

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], only: [:create, :destroy, :update], shallow: true do
      patch :best, on: :member
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :searches, only: [:index]

  mount ActionCable.server => "/cable"
end

app/models/question.rb
class Question < ApplicationRecord
  include Attachable
  include Authorable
  include Votable
  include Commentable

  has_many :answers, -> { order('best desc') }, dependent: :destroy
  has_many :subscribes, dependent: :destroy

  validates :title, :body, presence: true
  validates :title, :body, length: { minimum: 10 }

  after_create :subscribe_author

  scope :last_day, -> {  where("created_at >= ?", (Date.today - 1.day).to_time) }

  private

  def subscribe_author
    subscribes.create(author: author)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource class: Question

  def index
    respond_with Question.all
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question, serializer: QuestionFullSerializer
  end

  def create
    respond_with(@question = Question.create(question_params.merge(author: current_resource_owner)))
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :update, :destroy]
  before_action :build_answer, only: [:show]

  after_action :publish_question, only: [:create]

  respond_to :js, only: [:update]
  respond_to :json

  authorize_resource

  include Voted

  def index
    respond_with(@questions = Question.with_rating)
  end

  def show
    respond_with @question
  end

  def new
    respond_with(@question = Question.new)
  end

  def create
    respond_with(@question = Question.create(question_params.merge(author: current_user)))
  end

  def update
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      @question.to_json
    )
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def build_answer
    @answer = @question.answers.build
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/views/questions/_form.html.slim
= form_for question, remote: remote, html: { multipart: true, id: "edit_question_#{question.id}" } do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  .form-group
    = render 'shared/nested_form/attachments_form', f: f, attachable: question
  .form-group
    = f.submit class: 'btn btn-primary'

app/views/questions/_question.html.slim
.question id="question_#{question.id}" data-question-id="#{question.id}"
  .question-show
    = render 'shared/votes_panel', obj: question

    - if current_user && current_user.has_subscribe?(question)
      = link_to "Unsubscribe", subscribe_path(current_user.get_subscribe(question)), remote: true, method: :delete, id: "unsubscribe_btn", class: "btn btn-primary"
    - else
      - if can?(:create, Subscribe)
        = link_to "Subscribe", question_subscribes_path(question), remote: true, method: :post, id: "subscribe_btn", class: "btn btn-primary"

    - if can?(:update, question)
      = link_to 'Edit', '', class: 'edit-question-link btn btn-primary', data: { question_id: question.id }
      = render 'form', question: question, remote: true

    - cache question do
      h1= question.title
      p= question.body
      = render partial: 'shared/nested_form/attachments', locals: { obj: question }

  = render 'comments/comments', commentable: question

app/views/questions/index.html.slim
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path, class: 'btn btn-primary'

table.table.questions-list
  thead
    tr
      th Question
      th
  tbody
    - @questions.each do |question|
      tr
        td.clearfix
          = render 'shared/votes_panel', obj: question
          = link_to question.title, question
        td
          - if can?(:destroy, question)
            = link_to 'Remove question', question,
              method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm'

app/views/questions/new.html.slim
= render 'form', question: @question, remote: false

app/views/questions/show.html.slim
.jumbotron = render @question

- unless @question.answers.empty?
  #answers= render @question.answers.with_rating

- if can?(:create, Answer)
  = form_for [@question, @answer], remote: true do |f|
    fieldset
      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control'
      = render 'shared/nested_form/attachments_form', f: f, attachable: @answer
      .form-group
      = f.submit class: 'btn btn-primary'
- else
   p To answer the question log in

app/views/questions/update.js.erb
$('#flash').replaceWith('<%= j render partial: "shared/flash_message" %>');
$('#errors_block').remove();

<% if @question.errors.present? %>
  $("form#edit_question_<%= @question.id %>").before('<%= j render partial: "shared/error_messages", locals: { obj: @question } %>');
<% else %>
  $('.question').replaceWith("<%= j render @question %>");

  $('.edit-question-link').click(function(e) {
    $(this).hide();
    question_id = $(this).data('questionId');
    $('form#edit_question_' + question_id).show();
    e.preventDefault();
  });
<% end %>