config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', confirmations: 'confirmations' }

  root to: "questions#index"

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], only: [:create, :destroy, :update], shallow: true do
      patch :best, on: :member
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :searches, only: [:index]

  mount ActionCable.server => "/cable"
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Authorable
  include Votable
  include Commentable

  belongs_to :question, touch: true

  validates :body, presence: true
  validates :body, length: { minimum: 10 }
  validates :best, uniqueness: { scope: :question_id }, if: :best?

  after_create :notify_subscribed_users

  def mark_as_best
    transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
    end
  end

  private

  def notify_subscribed_users
    NotifySubscribedUsersJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, except: [:create]
  before_action :set_question, only: [:create]

  after_action :publish_answer, only: [:create]

  respond_to :js

  authorize_resource

  include Voted

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(author: current_user)))
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def update
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def best
    @answer.mark_as_best
    respond_with(@answer)
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "answers_#{@question.id}",
      { answer: @answer, attachments: @answer.attachments }.to_json
    )
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource class: Answer

  def index
    question = Question.find(params[:question_id])
    respond_with question.answers.reorder('id')
  end

  def show
    answer = Answer.find(params[:id])
    respond_with answer, serializer: AnswerFullSerializer
  end

  def create
    question = Question.find(params[:question_id])
    respond_with(@answer = question.answers.create(answer_params.merge(author: current_resource_owner)))
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div.answer.clearfix id = "answer_#{answer.id}"
    = render 'shared/votes_panel', obj: answer

    ul.list-inline
      - if answer.best?
        li
          strong Best answer
      - if user_signed_in?
        - if !answer.best? && can?(:best, answer)
          li= link_to 'Best', best_answer_path(answer), method: :patch, remote: true, class: 'btn btn-success btn-sm'
        - if can?(:update, answer)
          li= link_to 'Edit', '', class: 'edit_answer_link btn btn-primary btn-sm', data: { answer_id: answer.id }
          li= link_to 'Remove answer', answer, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
          = form_for answer, remote: true do |f|
            fieldset
              .form-group
                = f.label :body, 'Answer'
                = f.text_area :body, class: 'form-control'
              = render 'shared/nested_form/attachments_form', f: f, attachable: answer
              .form-group
                = f.submit 'Save', class: 'btn btn-primary'

    - cache answer do
      p= answer.body
      = render partial: 'shared/nested_form/attachments', locals: { obj: answer }

      = render 'comments/comments', commentable: answer

app/views/answers/best.js.erb
$('#flash').replaceWith("<%= j render partial: 'shared/flash_message' %>");
$("#answers").html("<%= j render @answer.question.answers %>");

app/views/answers/create.js.erb
$('#flash').remove();
$('#errors_block').remove();
$('.main').prepend('<%= j render partial: "shared/flash_message" %>');

<% if @answer.errors.any? %>
  $('#new_answer').before('<%= j render partial: "shared/error_messages", locals: { obj: @answer } %>');
<% else %>
  $('form#new_answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#flash').replaceWith("<%= j render partial: 'shared/flash_message' %>");

$('#answer_' + <%= params[:id] %>).remove();

app/views/answers/update.js.erb
$('#flash').replaceWith("<%= j render partial: 'shared/flash_message' %>");
$('#errors_block').remove();

<% if @answer.errors.present? %>
  $("form#edit_answer_<%= @answer.id %>").before("<%= j render partial: 'shared/error_messages', locals: { obj: @answer } %>");
<% else %>
  $('#answer_' + <%= @answer.id %>).replaceWith("<%= j render partial: 'answer', locals: { answer: @answer } %>");
<% end %>

$('.edit_answer_link').click(function(e) {
  e.preventDefault();
  $(this).hide();
  answer_id = $(this).data('answerId');
  $('#edit_answer_' + answer_id).show();
});