config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', confirmations: 'confirmations' }

  root to: "questions#index"

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], only: [:create, :destroy, :update], shallow: true do
      patch :best, on: :member
    end
    resources :subscribes, only: [:create, :destroy], shallow: true
  end

  resources :attachments, only: [:destroy]

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end

  resources :searches, only: [:index]

  mount ActionCable.server => "/cable"
end

app/views/shared/nested_form/_attachments.slim
ul.attachments.list-inline
  - obj.attachments.each do |a|
    - if a.persisted?
      li class = "attachment_#{a.id}"
        = link_to a.file.filename, a.file.url
        | &nbsp;
        - if can?(:destroy, a)
          span.remove_attachment_btn
            = link_to 'x', attachment_path(a), method: :delete, remote: true, data: { confirm: 'Are you sure?' }

app/views/shared/nested_form/_attachments_form.html.slim
p Attachments:

.attachment_form_fields
  = f.fields_for :attachments, attachable.attachments.build do |attachment|
    = render 'shared/nested_form/attachments_form_fields', f: attachment
  .links
    = link_to_add_association 'add file', f, :attachments,
            partial: 'shared/nested_form/attachments_form_fields'

app/views/shared/nested_form/_attachments_form_fields.html.slim
.nested_fields
  .field
    - if f.object.persisted?
      = f.object.file.filename
    - else
      = f.label :file
      = f.file_field :file
  = link_to_remove_association 'remove file', f, { wrapper_class: 'nested_fields' }